export default ImageControl;
declare class ImageControl {
    constructor(options?: import("./types").ControlOptions);
    container: HTMLDivElement;
    fileInput: HTMLInputElement;
    buttonAdd: HTMLButtonElement;
    buttonMove: HTMLButtonElement;
    buttonScale: HTMLButtonElement;
    buttonRotate: HTMLButtonElement;
    buttonRemove: HTMLButtonElement | undefined;
    rasters: Record<string, Raster>;
    currentRaster: Raster | null;
    currentMode: Move | Scale | Rotate | null;
    addFile(file: File, coordinates?: import("./types").RasterCoordinates | undefined): Promise<string>;
    addUrl(url: string, coordinates?: import("./types").RasterCoordinates | undefined): Promise<string>;
    addImage(image: HTMLImageElement, coordinates?: import("./types").RasterCoordinates | undefined): Promise<string>;
    addRaster(raster: Raster): void;
    removeRaster(): void;
    selectRaster(id: string): void;
    deselectRaster(): void;
    setMode(mode: "move" | "scale" | "rotate" | null): void;
    updateCoordinates(coordinates: import("./types").RasterCoordinates): void;
    onMapClick: (event: import("mapbox-gl").MapMouseEvent) => void;
    setLock: (id: string, isLocked: boolean) => void;
    onAdd(map: import("mapbox-gl").Map): HTMLElement;
    map: import("mapbox-gl").Map | undefined;
    onRemove(): void;
}
import { Raster } from './raster.js';
import { Move } from './modes/move.js';
import { Scale } from './modes/scale.js';
import { Rotate } from './modes/rotate.js';
